# Netlify Configuration
[build]
  publish = "."
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "*.pdf"
  [headers.values]
    Content-Disposition = "inline"

[[redirects]]
  from = "/resume"
  to = "/assets/resume.pdf"
  status = 200

[[redirects]]
  from = "/cv"
  to = "/assets/resume.pdf"
  status = 200
